// Copy adapted from the supplied ReadFirst wireframe and keyword documents.
// Keep unverified programme details, studies and outcomes out of public content.
export const pages = {
  learning: { title: 'Learning should create learners.', label: 'Learn how to learn', intro: 'Learning develops more than knowledge. It develops the ability to understand, question, reflect and continue learning independently.', sections: [['Deep learning', 'Move beyond surface-level memorisation towards genuine understanding.'], ['Self-learning', 'Develop the ability and confidence to engage with learning without constant instruction, using appropriate guidance, resources and collaboration.'], ['Independent thinking', 'Question, analyse and form your own understanding.']], links: [['Explore purposeful reading', '/reading'], ['Discover SMILE', '/smile']] },
  reading: { title: 'Read to understand. Read to think.', label: 'Purposeful reading', intro: 'ReadFirst uses textbooks and reading as tools for deep learning and independent thinking.', sections: [['Deep reading', 'Give ideas the attention they need. Reading can create space to understand, question and reflect.'], ['Active reading', 'Engage with the meaning of a text rather than simply consuming information.'], ['A reading culture', 'Create learning environments where books, curiosity and reflection support independent learners.']], links: [['Explore student programmes', '/students'], ['Build a learning culture', '/schools']] },
  students: { title: 'Become a learner. Not just a student.', label: 'For students', audience: 'Students', intro: 'ReadFirst’s student programmes focus on developing the learner behind the marks: awareness, purposeful reading, understanding and independent thinking.', sections: [['14-Day Mindfulness Programme', 'Pause. Observe. Reset. Develop awareness, attention, focus, presence, concentration and mental readiness for learning.'], ['30-Day Accelerate Your Learning', 'Learn how to learn. Develop as a self-learner, independent thinker and deeper learner through the SMILE Learning Model, textbooks, reading and reflection.']], links: [['Explore Mindfulness', '/mindfulness'], ['Explore Accelerate Your Learning', '/accelerate-your-learning']] },
  mindfulness: { title: 'Pause. Observe. Reset.', label: '14-Day Mindfulness Programme', audience: 'Students', intro: 'A learner-development experience focused on greater awareness, attention and mental readiness for learning.', sections: [['Make room for attention', 'Explore awareness, focus, presence and concentration as part of the learning journey.'], ['Prepare to learn', 'Mindfulness is part of developing the learner: taking time to observe and reflect before engaging with learning.']], links: [['Explore Accelerate Your Learning', '/accelerate-your-learning']] },
  'accelerate-your-learning': { title: 'Learn how to learn.', label: '30-Day Accelerate Your Learning', audience: 'Students', intro: 'Develop as a self-learner, independent thinker and deeper learner. The central proposition is learning how to learn, rather than simply studying faster.', sections: [['Understanding through reading', 'Use textbooks and purposeful reading to engage with ideas and build deep understanding.'], ['Learning independence', 'The programme uses the SMILE Learning Model and focuses on deep learning, self-learning, independent thinking and reduced screen dependence.']], links: [['Explore the SMILE Learning Model', '/smile'], ['Explore Mindfulness', '/mindfulness']] },
  educators: { title: 'Understand learning deeply enough to transform practice.', label: 'Research-Based Teaching & Learning', audience: 'Educators', cta: 'Apply to the Programme', intro: 'For educators who believe teaching can be more than delivering a syllabus. A serious, research-led learning experience for those ready to rethink how learning happens.', sections: [['Understand the learner', 'Explore how students learn and understand, what influences learning behaviour and how educators can guide them more effectively.'], ['Rethink teaching practice', 'The programme focuses on reflective practice, teacher transformation and the role of the Learning Coach. Its purpose goes beyond adding another set of classroom techniques.'], ['Participation is intentionally selective', 'Screening considers curiosity, openness to questioning existing practices, willingness to reflect, seriousness about learning and genuine interest in understanding students.']], links: [['Explore the ReadFirst approach', '/smile']] },
  schools: { title: 'Build a culture of independent learning.', label: 'For schools & colleges', audience: 'Institutions', intro: 'ReadFirst works with educational institutions to create environments that encourage deeper engagement with learning, curiosity, reading, reflection and independent learning.', sections: [['The Learning Marathon — TLM', 'An institutional learning offering that connects educator development with the wider learning culture.'], ['From syllabus completion to genuine learning', 'Make space for curiosity and exploration, purposeful reading and independent thinking.']], links: [['Explore The Learning Marathon', '/the-learning-marathon'], ['Explore educator development', '/educators']] },
  'the-learning-marathon': { title: 'A learning culture. Across your institution.', label: 'The Learning Marathon — TLM', audience: 'Institutions', cta: 'Enquire about TLM', intro: 'The Learning Marathon is ReadFirst’s institutional learning offering, designed around deeper engagement with learning, curiosity, reading, reflection and independent learning.', sections: [['Beyond a standalone course', 'Educator development is part of a wider institutional proposition: an environment that helps students become independent learners.'], ['The shift we work towards', 'From syllabus completion to genuine learning. From instruction to independent thinking. From information consumption to exploration.'], ['Start with your institution', 'Tell us what you would like to understand or change in your learning environment.']], links: [['Explore research-based teaching', '/educators']] },
  smile: { title: 'SMILE', label: 'The ReadFirst learning model', intro: 'Self-Motivated Intelligent Learning Environment. The model through which ReadFirst approaches learning.', sections: [['The learner comes first', 'SMILE brings together the conditions and behaviours that support deep learning, self-learning and independent thinking.'], ['Reading. Reflection. Learning independence.', 'The model connects purposeful reading and reflection with reduced dependence on constant instruction and screens.'], ['Technology serves the learning need', 'ReadFirst starts with the learner and asks what supports meaningful learning. Technology is a resource, rather than the starting point.']], links: [['For students', '/students'], ['For educators', '/educators'], ['For schools & colleges', '/schools']] },
  research: { title: 'Questions are where research begins.', label: 'Research & Insights', intro: 'Research-based learning and teaching begin with understanding the learner. Explore the questions that shape ReadFirst’s approach.', sections: [['How do students learn?', 'Understanding learning behaviour helps us ask what supports deep learning and learner independence.'], ['What makes reading purposeful?', 'How can reading help a learner understand, question and think independently?'], ['How can educators transform practice?', 'Observation, curiosity and reflective practice create space to rethink the learning environment.']], links: [['Explore the learning model', '/smile'], ['Explore reflective teaching practice', '/educators']] },
  about: { title: 'Building a different way of learning.', label: 'About ReadFirst', intro: 'ReadFirst is a learning-focused organisation working with students, educators and educational institutions to develop deeper learning, purposeful reading, self-learning and independent thinking.', sections: [['Our belief', 'Learning should create learners. It should develop the ability to understand, question, reflect and continue learning independently.'], ['Our starting point', 'We start with the learner: how they learn, how they understand and what helps them become independent.'], ['One learning ecosystem', 'ReadFirst works with schools and colleges through The Learning Marathon, educators through Research-Based Teaching & Learning, and students through Mindfulness and Accelerate Your Learning.']], links: [['Our learning model', '/smile'], ['Who we work with', '/#who-we-work-with']] },
  contact: { title: 'Start with a question.', label: 'Get in touch', intro: 'Tell us what you’re trying to understand, change or explore. Choose the pathway that best describes you.', sections: [], links: [] },
};
export const faqs = [
  ['General', [
    ['What is ReadFirst?', pages.about.intro],
    ['Is ReadFirst an EdTech company?', 'ReadFirst does not begin with technology. It begins with the learner and with understanding how learning happens.'],
    ['What makes ReadFirst different?', 'ReadFirst focuses on how people learn, understand, question, reflect and become independent learners rather than simply delivering content or classroom techniques.'],
    ['Why focus on learning how to learn?', 'Learning is about both what a learner knows today and the ability to continue learning independently.'],
  ]],
  ['Students', [
    ['What do students learn through ReadFirst?', 'Students develop habits and capabilities around reading, understanding, curiosity, focus, self-learning and independent thinking.'],
    ['What is the 14-Day Mindfulness Programme?', pages.mindfulness.intro],
    ['What is Accelerate Your Learning?', 'A 30-day learning experience focused on helping students become self-learners, independent thinkers and deeper learners.'],
    ['Is Accelerate Your Learning about studying faster?', 'Its central proposition is Learn How to Learn, rather than simply learning faster.'],
  ]],
  ['Educators', [
    ['Is this conventional teacher training?', 'It is a serious learning experience designed to help educators understand learning deeply enough to transform their own practice.'],
    ['Who is the programme for?', 'Educators who are curious, reflective, serious about learning and willing to question and rethink existing practice.'],
    ['Why is the educator programme selective?', 'The experience requires curiosity, openness, reflection and a willingness to rethink how learning happens.'],
    ['Will educators learn classroom techniques?', 'The programme is not primarily about adding another set of classroom techniques. It focuses on understanding learning deeply enough to transform practice.'],
  ]],
  ['Schools & Colleges', [
    ['What is The Learning Marathon (TLM)?', pages['the-learning-marathon'].intro],
    ['Is TLM just a teacher-training programme?', 'TLM is an institutional learning offering. Educator development is part of the wider institutional learning proposition.'],
    ['Who can work with ReadFirst?', 'Schools and educational institutions interested in stronger learning cultures, independent learners, reading, research-based education and deeper engagement with learning.'],
    ['What is a learning culture?', 'An environment where learning goes beyond instruction and syllabus completion to include curiosity, reading, reflection, inquiry and independent learning.'],
  ]],
  ['Approach', [
    ['What is SMILE?', 'SMILE stands for Self-Motivated Intelligent Learning Environment. It is the learning model behind the ReadFirst approach.'],
    ['Is SMILE a course?', 'SMILE is the learning model through which ReadFirst approaches learning.'],
    ['Does ReadFirst reject technology?', 'No. Technology should serve the learning need rather than become the starting point.'],
    ['What does independent learning mean?', 'Developing the ability and confidence to engage with learning without constant instruction, while using appropriate guidance, resources and collaboration.'],
  ]],
  ['Contact', [
    ['How do I start a conversation?', 'Choose School or College, Educator, Student or a general enquiry and tell us what you would like to understand, change or explore.'],
    ['Can I enquire about TLM for my institution?', 'Yes. Use the Schools & Colleges pathway and select The Learning Marathon.'],
    ['How can an educator apply?', 'Use the Educators pathway and choose Apply to the Programme. Participation is intentionally selective.'],
  ]],
];
